services:
  backend:
    image: ${DOCKER_HUB_USERNAME}/vrl-backend:latest
    container_name: vrl-backend
    ports:
      - "5000:5000"
    env_file:
      - .env.backend
    restart: always

  frontend:
    image: ${DOCKER_HUB_USERNAME}/vrl-frontend:latest
    container_name: vrl-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.frontend
    depends_on:
      - backend
    restart: always

#  nginx:
#    image: nginx:alpine
#    container_name: nginx
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#      - /etc/letsencrypt/live/vrlinstitute.lk/fullchain.pem:/etc/letsencrypt/live/vrlinstitute.lk/fullchain.pem:ro
#      - /etc/letsencrypt/live/vrlinstitute.lk/privkey.pem:/etc/letsencrypt/live/vrlinstitute.lk/privkey.pem:ro
#    depends_on:
#      - frontend
#      - backend
#    restart: always